// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

AddressInfo validateAddress({required String addressStr}) =>
    RustLib.instance.api.crateAddressValidateAddress(addressStr: addressStr);

Future<AddressInfo> validateAddressInternal({required String addressStr}) =>
    RustLib.instance.api
        .crateAddressValidateAddressInternal(addressStr: addressStr);

bool isValidBech32({required String addr}) =>
    RustLib.instance.api.crateAddressIsValidBech32(addr: addr);

class AddressInfo {
  final String address;
  final String network;

  const AddressInfo({
    required this.address,
    required this.network,
  });

  @override
  int get hashCode => address.hashCode ^ network.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AddressInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          network == other.network;
}
