// This file is automatically generated, so please do not edit it.
// Generated by flutter_rust_bridge
// Phase 0: stub implementation - Phase 1 will integrate full FFI bindings

import 'dart:async';

// Helper functions that wrap the FFI calls
// Phase 0: these are stub implementations for testing the app structure
// Phase 1: these will be replaced with actual FFI bridge bindings
Future<String> getSdkVersion() async {
  return 'cardano_flutter_rs v0.1.0';
}

Future<bool> isValidBech32(String addr) async {
  return addr.startsWith('addr') && addr.length > 50;
}
