// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tx.dart';

// These functions are ignored because they are not marked as `pub`: `address_label`, `blake2b_256`, `csl_value_to_value`, `map_cms_err`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Compute a bech32 base address from payment and stake key hashes.
///
/// A base address binds a payment credential and a staking credential, e.g.
/// `addr_test1q…` (testnet) or `addr1q…` (mainnet). This is the address a
/// CIP-30 wallet returns from `getChangeAddress` / `getUsedAddresses`.
///
/// # Arguments
/// - `payment_key_hash_hex`: 56-char hex Blake2b-224 payment key hash
/// - `stake_key_hash_hex`: 56-char hex Blake2b-224 stake key hash
/// - `network_id`: 0 = testnet, 1 = mainnet
String computeBaseAddress(
        {required String paymentKeyHashHex,
        required String stakeKeyHashHex,
        required int networkId}) =>
    RustLib.instance.api.crateCip30ComputeBaseAddress(
        paymentKeyHashHex: paymentKeyHashHex,
        stakeKeyHashHex: stakeKeyHashHex,
        networkId: networkId);

/// Convert a bech32 address to hex of its raw bytes (CIP-30 address encoding).
String addressToHex({required String addressBech32}) =>
    RustLib.instance.api.crateCip30AddressToHex(addressBech32: addressBech32);

/// Serialize a [`Value`] to CBOR hex (CIP-30 `getBalance` encoding).
String valueToCborHex({required Value value}) =>
    RustLib.instance.api.crateCip30ValueToCborHex(value: value);

/// Serialize a [`TxInput`] to a CBOR `TransactionUnspentOutput` hex string
/// (CIP-30 `getUtxos` encoding: `[input, output]`).
String utxoToCborHex({required TxInput input}) =>
    RustLib.instance.api.crateCip30UtxoToCborHex(input: input);

/// Sum a list of [`Value`]s into a single [`Value`] (coin + native assets).
///
/// Used to compute a wallet's total balance from its UTxO set. Multi-asset
/// addition is delegated to CSL for correctness.
Value sumValues({required List<Value> values}) =>
    RustLib.instance.api.crateCip30SumValues(values: values);

/// Sign a full transaction and return only the vkey witness set (CBOR hex).
///
/// CIP-30 `signTx` hands the wallet a complete transaction and expects back a
/// `cbor<transaction_witness_set>` containing the wallet's witnesses, which the
/// dApp then merges with the body before submission.
///
/// Only the witnesses for the supplied keys are produced; any witnesses already
/// present in the transaction are not echoed back.
///
/// # Arguments
/// - `tx_cbor_hex`: full transaction (body + witnesses + aux) as CBOR hex
/// - `signing_keys_bech32`: bech32 xprv keys to sign with (payment, stake, …)
String cip30SignTx(
        {required String txCborHex, required List<String> signingKeysBech32}) =>
    RustLib.instance.api.crateCip30Cip30SignTx(
        txCborHex: txCborHex, signingKeysBech32: signingKeysBech32);

/// Assemble a full transaction CBOR from a body, a witness set, and optional
/// auxiliary data.
///
/// This is the dApp-side counterpart to [`cip30_sign_tx`]: the dApp builds the
/// body, the wallet returns a `transaction_witness_set`, and this combines them
/// into a submittable transaction. To build an *unsigned* transaction to hand to
/// `signTx`, pass an empty witness set (`"a0"`).
///
/// # Arguments
/// - `tx_body_cbor_hex`: transaction body CBOR hex
/// - `witness_set_cbor_hex`: `transaction_witness_set` CBOR hex
/// - `aux_data_cbor_hex`: optional auxiliary-data CBOR hex
String cip30AssembleTx(
        {required String txBodyCborHex,
        required String witnessSetCborHex,
        String? auxDataCborHex}) =>
    RustLib.instance.api.crateCip30Cip30AssembleTx(
        txBodyCborHex: txBodyCborHex,
        witnessSetCborHex: witnessSetCborHex,
        auxDataCborHex: auxDataCborHex);

/// Sign arbitrary data per CIP-30 `signData` (CIP-8 `COSE_Sign1`).
///
/// Produces a `COSE_Sign1` whose protected headers carry `alg = EdDSA` and the
/// signer `address`, with `hashed = false`, plus a matching `COSE_Key` — the
/// exact shape produced by browser wallets, since both are built with Emurgo's
/// `cardano-message-signing` reference library.
///
/// # Arguments
/// - `address_hex`: hex of the raw signer address bytes (see [`address_to_hex`])
/// - `payload_hex`: hex of the message bytes to sign
/// - `signing_key_bech32`: bech32 xprv signing key
///
/// # Returns
/// A [`DataSignature`] with the `COSE_Sign1` and `COSE_Key` as hex CBOR.
DataSignature cip30SignData(
        {required String addressHex,
        required String payloadHex,
        required String signingKeyBech32}) =>
    RustLib.instance.api.crateCip30Cip30SignData(
        addressHex: addressHex,
        payloadHex: payloadHex,
        signingKeyBech32: signingKeyBech32);

/// Verify a CIP-30 `DataSignature`.
///
/// Parses the `COSE_Sign1` with the reference library, reconstructs the
/// `Sig_structure`, and verifies the Ed25519 signature against the public key
/// embedded in the `COSE_Key`.
///
/// # Arguments
/// - `data_signature`: the [`DataSignature`] to verify
/// - `expected_payload_hex`: if provided, the embedded payload must match it
///
/// # Returns
/// `true` if the signature is valid (and the payload matches, if given).
bool cip30VerifyData(
        {required DataSignature dataSignature, String? expectedPayloadHex}) =>
    RustLib.instance.api.crateCip30Cip30VerifyData(
        dataSignature: dataSignature, expectedPayloadHex: expectedPayloadHex);

/// A CIP-30 `DataSignature`: a COSE_Sign1 signature plus its COSE_Key.
///
/// Both fields are hex-encoded CBOR, matching the shape a CIP-30 `signData`
/// call returns to a dApp (`{ signature, key }`).
class DataSignature {
  /// Hex-encoded `COSE_Sign1` structure (`[protected, unprotected, payload, sig]`).
  final String signature;

  /// Hex-encoded `COSE_Key` containing the Ed25519 public key.
  final String key;

  const DataSignature({
    required this.signature,
    required this.key,
  });

  @override
  int get hashCode => signature.hashCode ^ key.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DataSignature &&
          runtimeType == other.runtimeType &&
          signature == other.signature &&
          key == other.key;
}
