// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tx.dart';

// These functions are ignored because they are not marked as `pub`: `aggregate_assets`, `checked_sum`, `estimate_fee_for_inputs`, `estimate_min_ada_for_multi_asset_output`, `estimate_min_ada`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Implements CIP-2 largest-first coin selection.
///
/// Selects a minimal set of inputs from `available_utxos` that cover
/// `target_outputs`, estimated fees, and minimum change ADA, prioritizing
/// larger inputs to minimize the number of UTXOs consumed.
///
/// # Arguments
///
/// * `available_utxos` - Pool of unspent outputs to select from.
/// * `target_outputs` - Desired payment outputs (not including change).
/// * `change_address` - Address to send change to.
/// * `params` - Network protocol parameters (fees, min-ada).
///
/// # Errors
///
/// - `CardanoError::InsufficientFunds` if total available < target + fee + min_change.
/// - `CardanoError::InsufficientAsset` if no UTXOs carry a required native asset.
/// - `CardanoError::DustChange` if change would be below min-ada and no more inputs available.
///
/// # Example
///
/// ```ignore
/// let utxos = vec![
///     TxInput { tx_hash: "aaa...".to_string(), output_index: 0, address: "addr...".to_string(), value: Value { coin: 2_000_000, assets: vec![] } },
///     TxInput { tx_hash: "bbb...".to_string(), output_index: 0, address: "addr...".to_string(), value: Value { coin: 1_000_000, assets: vec![] } },
/// ];
/// let targets = vec![
///     TxOutput { address: "addr_recv...".to_string(), value: Value { coin: 1_500_000, assets: vec![] } },
/// ];
/// let result = largest_first(utxos, targets, "addr_change...".to_string(), params)?;
/// assert_eq!(result.selected_inputs.len(), 1);
/// ```
Future<CoinSelectionResult> largestFirst(
        {required List<TxInput> availableUtxos,
        required List<TxOutput> targetOutputs,
        required String changeAddress,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateCoinSelectionLargestFirst(
        availableUtxos: availableUtxos,
        targetOutputs: targetOutputs,
        changeAddress: changeAddress,
        params: params);

/// Result of successful coin selection.
class CoinSelectionResult {
  /// UTXOs selected to cover outputs and fees.
  final List<TxInput> selectedInputs;

  /// Change output(s); typically one pure-ADA output plus optional multi-asset outputs.
  final List<TxOutput> changeOutputs;

  /// Computed transaction fee.
  final BigInt fee;

  const CoinSelectionResult({
    required this.selectedInputs,
    required this.changeOutputs,
    required this.fee,
  });

  @override
  int get hashCode =>
      selectedInputs.hashCode ^ changeOutputs.hashCode ^ fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CoinSelectionResult &&
          runtimeType == other.runtimeType &&
          selectedInputs == other.selectedInputs &&
          changeOutputs == other.changeOutputs &&
          fee == other.fee;
}
