// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

@freezed
sealed class CardanoError with _$CardanoError implements FrbException {
  const CardanoError._();

  const factory CardanoError.invalidAddress(
    String field0,
  ) = CardanoError_InvalidAddress;
  const factory CardanoError.invalidMnemonic(
    String field0,
  ) = CardanoError_InvalidMnemonic;
  const factory CardanoError.derivationError(
    String field0,
  ) = CardanoError_DerivationError;
  const factory CardanoError.serializationError(
    String field0,
  ) = CardanoError_SerializationError;
  const factory CardanoError.networkError(
    String field0,
  ) = CardanoError_NetworkError;
  const factory CardanoError.invalidKey(
    String field0,
  ) = CardanoError_InvalidKey;
  const factory CardanoError.invalidCbor(
    String field0,
  ) = CardanoError_InvalidCbor;
  const factory CardanoError.cslError(
    String field0,
  ) = CardanoError_CslError;
  const factory CardanoError.insufficientFunds({
    required BigInt neededLovelace,
    required BigInt availableLovelace,
  }) = CardanoError_InsufficientFunds;
  const factory CardanoError.insufficientAsset({
    required String policyId,
    required String assetName,
    required BigInt needed,
    required BigInt available,
  }) = CardanoError_InsufficientAsset;
  const factory CardanoError.dustChange({
    required BigInt residualLovelace,
    required BigInt minRequired,
  }) = CardanoError_DustChange;
  const factory CardanoError.coinSelectionError(
    String field0,
  ) = CardanoError_CoinSelectionError;
  const factory CardanoError.txBuild({
    required String reason,
  }) = CardanoError_TxBuild;
  const factory CardanoError.invalidParameter({
    required String field,
    required String reason,
  }) = CardanoError_InvalidParameter;
}
