// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

@freezed
sealed class CardanoError with _$CardanoError implements FrbException {
  const CardanoError._();

  const factory CardanoError.invalidAddress(
    String field0,
  ) = CardanoError_InvalidAddress;
  const factory CardanoError.invalidMnemonic(
    String field0,
  ) = CardanoError_InvalidMnemonic;
  const factory CardanoError.derivationError(
    String field0,
  ) = CardanoError_DerivationError;
  const factory CardanoError.serializationError(
    String field0,
  ) = CardanoError_SerializationError;
  const factory CardanoError.networkError(
    String field0,
  ) = CardanoError_NetworkError;
  const factory CardanoError.invalidKey(
    String field0,
  ) = CardanoError_InvalidKey;
  const factory CardanoError.cslError(
    String field0,
  ) = CardanoError_CslError;
}
