// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'address.dart';
import 'cip30.dart';
import 'coin_selection.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'hardware.dart';
import 'lib.dart';
import 'message.dart';
import 'metadata.dart';
import 'minting.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'plutus.dart';
import 'sign.dart';
import 'staking.dart';
import 'tx.dart';
import 'wallet.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AddressInfo dco_decode_address_info(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DataSignature dco_decode_box_autoadd_data_signature(dynamic raw);

  @protected
  ProtocolParams dco_decode_box_autoadd_protocol_params(dynamic raw);

  @protected
  SignedMessage dco_decode_box_autoadd_signed_message(dynamic raw);

  @protected
  TxInput dco_decode_box_autoadd_tx_input(dynamic raw);

  @protected
  TxOutput dco_decode_box_autoadd_tx_output(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  Value dco_decode_box_autoadd_value(dynamic raw);

  @protected
  BuiltMintTx dco_decode_built_mint_tx(dynamic raw);

  @protected
  BuiltStakingTx dco_decode_built_staking_tx(dynamic raw);

  @protected
  BuiltTx dco_decode_built_tx(dynamic raw);

  @protected
  CardanoError dco_decode_cardano_error(dynamic raw);

  @protected
  Cip25Asset dco_decode_cip_25_asset(dynamic raw);

  @protected
  Cip25Policy dco_decode_cip_25_policy(dynamic raw);

  @protected
  CoinSelectionResult dco_decode_coin_selection_result(dynamic raw);

  @protected
  DataSignature dco_decode_data_signature(dynamic raw);

  @protected
  DerivedAddress dco_decode_derived_address(dynamic raw);

  @protected
  HardwareAccount dco_decode_hardware_account(dynamic raw);

  @protected
  HardwareTxAsset dco_decode_hardware_tx_asset(dynamic raw);

  @protected
  HardwareTxBody dco_decode_hardware_tx_body(dynamic raw);

  @protected
  HardwareTxInput dco_decode_hardware_tx_input(dynamic raw);

  @protected
  HardwareTxOutput dco_decode_hardware_tx_output(dynamic raw);

  @protected
  HardwareVkeyWitness dco_decode_hardware_vkey_witness(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  KeyDerivationResult dco_decode_key_derivation_result(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Cip25Asset> dco_decode_list_cip_25_asset(dynamic raw);

  @protected
  List<Cip25Policy> dco_decode_list_cip_25_policy(dynamic raw);

  @protected
  List<HardwareTxAsset> dco_decode_list_hardware_tx_asset(dynamic raw);

  @protected
  List<HardwareTxInput> dco_decode_list_hardware_tx_input(dynamic raw);

  @protected
  List<HardwareTxOutput> dco_decode_list_hardware_tx_output(dynamic raw);

  @protected
  List<HardwareVkeyWitness> dco_decode_list_hardware_vkey_witness(dynamic raw);

  @protected
  List<MintAsset> dco_decode_list_mint_asset(dynamic raw);

  @protected
  List<MintSpec> dco_decode_list_mint_spec(dynamic raw);

  @protected
  List<NativeAsset> dco_decode_list_native_asset(dynamic raw);

  @protected
  List<PlutusInput> dco_decode_list_plutus_input(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TxInput> dco_decode_list_tx_input(dynamic raw);

  @protected
  List<TxOutput> dco_decode_list_tx_output(dynamic raw);

  @protected
  List<Value> dco_decode_list_value(dynamic raw);

  @protected
  MintAsset dco_decode_mint_asset(dynamic raw);

  @protected
  MintSpec dco_decode_mint_spec(dynamic raw);

  @protected
  NativeAsset dco_decode_native_asset(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  PlutusInput dco_decode_plutus_input(dynamic raw);

  @protected
  PlutusScriptVersion dco_decode_plutus_script_version(dynamic raw);

  @protected
  ProtocolParams dco_decode_protocol_params(dynamic raw);

  @protected
  SignedMessage dco_decode_signed_message(dynamic raw);

  @protected
  SignedTx dco_decode_signed_tx(dynamic raw);

  @protected
  TxInput dco_decode_tx_input(dynamic raw);

  @protected
  TxOutput dco_decode_tx_output(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Value dco_decode_value(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AddressInfo sse_decode_address_info(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DataSignature sse_decode_box_autoadd_data_signature(
      SseDeserializer deserializer);

  @protected
  ProtocolParams sse_decode_box_autoadd_protocol_params(
      SseDeserializer deserializer);

  @protected
  SignedMessage sse_decode_box_autoadd_signed_message(
      SseDeserializer deserializer);

  @protected
  TxInput sse_decode_box_autoadd_tx_input(SseDeserializer deserializer);

  @protected
  TxOutput sse_decode_box_autoadd_tx_output(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Value sse_decode_box_autoadd_value(SseDeserializer deserializer);

  @protected
  BuiltMintTx sse_decode_built_mint_tx(SseDeserializer deserializer);

  @protected
  BuiltStakingTx sse_decode_built_staking_tx(SseDeserializer deserializer);

  @protected
  BuiltTx sse_decode_built_tx(SseDeserializer deserializer);

  @protected
  CardanoError sse_decode_cardano_error(SseDeserializer deserializer);

  @protected
  Cip25Asset sse_decode_cip_25_asset(SseDeserializer deserializer);

  @protected
  Cip25Policy sse_decode_cip_25_policy(SseDeserializer deserializer);

  @protected
  CoinSelectionResult sse_decode_coin_selection_result(
      SseDeserializer deserializer);

  @protected
  DataSignature sse_decode_data_signature(SseDeserializer deserializer);

  @protected
  DerivedAddress sse_decode_derived_address(SseDeserializer deserializer);

  @protected
  HardwareAccount sse_decode_hardware_account(SseDeserializer deserializer);

  @protected
  HardwareTxAsset sse_decode_hardware_tx_asset(SseDeserializer deserializer);

  @protected
  HardwareTxBody sse_decode_hardware_tx_body(SseDeserializer deserializer);

  @protected
  HardwareTxInput sse_decode_hardware_tx_input(SseDeserializer deserializer);

  @protected
  HardwareTxOutput sse_decode_hardware_tx_output(SseDeserializer deserializer);

  @protected
  HardwareVkeyWitness sse_decode_hardware_vkey_witness(
      SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  KeyDerivationResult sse_decode_key_derivation_result(
      SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Cip25Asset> sse_decode_list_cip_25_asset(SseDeserializer deserializer);

  @protected
  List<Cip25Policy> sse_decode_list_cip_25_policy(SseDeserializer deserializer);

  @protected
  List<HardwareTxAsset> sse_decode_list_hardware_tx_asset(
      SseDeserializer deserializer);

  @protected
  List<HardwareTxInput> sse_decode_list_hardware_tx_input(
      SseDeserializer deserializer);

  @protected
  List<HardwareTxOutput> sse_decode_list_hardware_tx_output(
      SseDeserializer deserializer);

  @protected
  List<HardwareVkeyWitness> sse_decode_list_hardware_vkey_witness(
      SseDeserializer deserializer);

  @protected
  List<MintAsset> sse_decode_list_mint_asset(SseDeserializer deserializer);

  @protected
  List<MintSpec> sse_decode_list_mint_spec(SseDeserializer deserializer);

  @protected
  List<NativeAsset> sse_decode_list_native_asset(SseDeserializer deserializer);

  @protected
  List<PlutusInput> sse_decode_list_plutus_input(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TxInput> sse_decode_list_tx_input(SseDeserializer deserializer);

  @protected
  List<TxOutput> sse_decode_list_tx_output(SseDeserializer deserializer);

  @protected
  List<Value> sse_decode_list_value(SseDeserializer deserializer);

  @protected
  MintAsset sse_decode_mint_asset(SseDeserializer deserializer);

  @protected
  MintSpec sse_decode_mint_spec(SseDeserializer deserializer);

  @protected
  NativeAsset sse_decode_native_asset(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  PlutusInput sse_decode_plutus_input(SseDeserializer deserializer);

  @protected
  PlutusScriptVersion sse_decode_plutus_script_version(
      SseDeserializer deserializer);

  @protected
  ProtocolParams sse_decode_protocol_params(SseDeserializer deserializer);

  @protected
  SignedMessage sse_decode_signed_message(SseDeserializer deserializer);

  @protected
  SignedTx sse_decode_signed_tx(SseDeserializer deserializer);

  @protected
  TxInput sse_decode_tx_input(SseDeserializer deserializer);

  @protected
  TxOutput sse_decode_tx_output(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  Value sse_decode_value(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_address_info(AddressInfo self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_data_signature(
      DataSignature self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_protocol_params(
      ProtocolParams self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_signed_message(
      SignedMessage self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tx_input(TxInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tx_output(
      TxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_value(Value self, SseSerializer serializer);

  @protected
  void sse_encode_built_mint_tx(BuiltMintTx self, SseSerializer serializer);

  @protected
  void sse_encode_built_staking_tx(
      BuiltStakingTx self, SseSerializer serializer);

  @protected
  void sse_encode_built_tx(BuiltTx self, SseSerializer serializer);

  @protected
  void sse_encode_cardano_error(CardanoError self, SseSerializer serializer);

  @protected
  void sse_encode_cip_25_asset(Cip25Asset self, SseSerializer serializer);

  @protected
  void sse_encode_cip_25_policy(Cip25Policy self, SseSerializer serializer);

  @protected
  void sse_encode_coin_selection_result(
      CoinSelectionResult self, SseSerializer serializer);

  @protected
  void sse_encode_data_signature(DataSignature self, SseSerializer serializer);

  @protected
  void sse_encode_derived_address(
      DerivedAddress self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_account(
      HardwareAccount self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_tx_asset(
      HardwareTxAsset self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_tx_body(
      HardwareTxBody self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_tx_input(
      HardwareTxInput self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_tx_output(
      HardwareTxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_vkey_witness(
      HardwareVkeyWitness self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_key_derivation_result(
      KeyDerivationResult self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cip_25_asset(
      List<Cip25Asset> self, SseSerializer serializer);

  @protected
  void sse_encode_list_cip_25_policy(
      List<Cip25Policy> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hardware_tx_asset(
      List<HardwareTxAsset> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hardware_tx_input(
      List<HardwareTxInput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hardware_tx_output(
      List<HardwareTxOutput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_hardware_vkey_witness(
      List<HardwareVkeyWitness> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mint_asset(
      List<MintAsset> self, SseSerializer serializer);

  @protected
  void sse_encode_list_mint_spec(List<MintSpec> self, SseSerializer serializer);

  @protected
  void sse_encode_list_native_asset(
      List<NativeAsset> self, SseSerializer serializer);

  @protected
  void sse_encode_list_plutus_input(
      List<PlutusInput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_input(List<TxInput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_output(List<TxOutput> self, SseSerializer serializer);

  @protected
  void sse_encode_list_value(List<Value> self, SseSerializer serializer);

  @protected
  void sse_encode_mint_asset(MintAsset self, SseSerializer serializer);

  @protected
  void sse_encode_mint_spec(MintSpec self, SseSerializer serializer);

  @protected
  void sse_encode_native_asset(NativeAsset self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_plutus_input(PlutusInput self, SseSerializer serializer);

  @protected
  void sse_encode_plutus_script_version(
      PlutusScriptVersion self, SseSerializer serializer);

  @protected
  void sse_encode_protocol_params(
      ProtocolParams self, SseSerializer serializer);

  @protected
  void sse_encode_signed_message(SignedMessage self, SseSerializer serializer);

  @protected
  void sse_encode_signed_tx(SignedTx self, SseSerializer serializer);

  @protected
  void sse_encode_tx_input(TxInput self, SseSerializer serializer);

  @protected
  void sse_encode_tx_output(TxOutput self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_value(Value self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
