// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Derive a wallet [`HardwareAccount`] from a BIP-32 account-level xpub.
///
/// The xpub is the 64-byte CIP-1852 account key (`m/1852'/1815'/account'`) a
/// hardware wallet returns from its "get extended public key" call: 32 bytes of
/// raw Ed25519 public key followed by a 32-byte chain code. From it we soft-derive
/// the payment key (`…/0/0`) and stake key (`…/2/0`), hash each (Blake2b-224),
/// and assemble the base + reward addresses.
///
/// # Arguments
/// - `account_xpub_hex`: 128-char hex of the 64-byte account xpub
/// - `network_id`: 0 = testnet, 1 = mainnet
HardwareAccount xpubToAccount(
        {required String accountXpubHex, required int networkId}) =>
    RustLib.instance.api.crateHardwareXpubToAccount(
        accountXpubHex: accountXpubHex, networkId: networkId);

/// Assemble raw device vkey witnesses into a CBOR `transaction_witness_set`.
///
/// Hardware wallets return `(public_key, signature)` pairs rather than a CBOR
/// witness set. This packs them into a `TransactionWitnessSet` whose hex output
/// can be passed straight to [`crate::cip30::cip30_assemble_tx`] (or merged with
/// other witnesses) to build a submittable transaction.
///
/// # Arguments
/// - `witnesses`: device-produced `(vkey_hex, signature_hex)` pairs
String assembleVkeyWitnessSet({required List<HardwareVkeyWitness> witnesses}) =>
    RustLib.instance.api
        .crateHardwareAssembleVkeyWitnessSet(witnesses: witnesses);

/// Extract the raw vkey witnesses from a CBOR `transaction_witness_set`.
///
/// The inverse of [`assemble_vkey_witness_set`]. Useful for partial-signing and
/// multi-signature flows: pull the `(public_key, signature)` pairs out of a
/// witness set (e.g. one produced by software signing or another cosigner) to
/// merge them with witnesses from a hardware device.
///
/// Returns an empty list if the witness set carries no vkey witnesses.
///
/// # Arguments
/// - `witness_set_cbor_hex`: hex CBOR of a `TransactionWitnessSet`
List<HardwareVkeyWitness> extractVkeyWitnesses(
        {required String witnessSetCborHex}) =>
    RustLib.instance.api.crateHardwareExtractVkeyWitnesses(
        witnessSetCborHex: witnessSetCborHex);

/// A wallet account derived from a hardware-wallet (or watch-only) xpub.
///
/// All fields are derived purely from public-key material — no signing key is
/// ever required or produced.
class HardwareAccount {
  /// Bech32 base address (`addr…` / `addr_test…`) at role 0 / index 0.
  final String baseAddress;

  /// Bech32 reward (stake) address (`stake…` / `stake_test…`).
  final String rewardAddress;

  /// Blake2b-224 payment key hash (56 hex chars).
  final String paymentKeyHash;

  /// Blake2b-224 stake key hash (56 hex chars).
  final String stakeKeyHash;

  const HardwareAccount({
    required this.baseAddress,
    required this.rewardAddress,
    required this.paymentKeyHash,
    required this.stakeKeyHash,
  });

  @override
  int get hashCode =>
      baseAddress.hashCode ^
      rewardAddress.hashCode ^
      paymentKeyHash.hashCode ^
      stakeKeyHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HardwareAccount &&
          runtimeType == other.runtimeType &&
          baseAddress == other.baseAddress &&
          rewardAddress == other.rewardAddress &&
          paymentKeyHash == other.paymentKeyHash &&
          stakeKeyHash == other.stakeKeyHash;
}

/// A single Ed25519 vkey witness as returned by a hardware device.
class HardwareVkeyWitness {
  /// 32-byte raw Ed25519 public key, hex-encoded (64 hex chars).
  final String vkeyHex;

  /// 64-byte raw Ed25519 signature, hex-encoded (128 hex chars).
  final String signatureHex;

  const HardwareVkeyWitness({
    required this.vkeyHex,
    required this.signatureHex,
  });

  @override
  int get hashCode => vkeyHex.hashCode ^ signatureHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HardwareVkeyWitness &&
          runtimeType == other.runtimeType &&
          vkeyHex == other.vkeyHex &&
          signatureHex == other.signatureHex;
}
