// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `blake2b_256`, `public_key_owns_address`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CoseSign1`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Sign a message (arbitrary bytes) with a private key.
///
/// Uses Blake2b-256 to hash the message, then signs with the private key.
/// Returns a COSE Sign1 structure (CBOR encoded).
///
/// # Arguments
/// * `message` - Hex-encoded bytes to sign
/// * `signing_key_bech32` - Private key in bech32 format (xprv)
/// * `address` - Optional address for context (e.g., the sender's address)
///
/// # Returns
/// A [SignedMessage] containing the COSE Sign1 hex, public key, and address.
///
/// # Errors
/// * `InvalidKey` - If the signing key cannot be decoded
/// * `InvalidParameter` - If the message hex is malformed
SignedMessage signMessage(
        {required String message,
        required String signingKeyBech32,
        String? address}) =>
    RustLib.instance.api.crateMessageSignMessage(
        message: message, signingKeyBech32: signingKeyBech32, address: address);

Future<SignedMessage> signMessageInternal(
        {required String message,
        required String signingKeyBech32,
        String? address}) =>
    RustLib.instance.api.crateMessageSignMessageInternal(
        message: message, signingKeyBech32: signingKeyBech32, address: address);

/// Verify a CIP-8 signed message.
///
/// Verifies that the signature is a valid Ed25519 signature over the message
/// **and**, when an address is involved, that the signing public key actually
/// owns that address (identity binding — see the module docs).
///
/// # Arguments
/// * `signed_message` - The [SignedMessage] to verify
/// * `expected_address` - Optional: if provided, must equal `signed_message.address`,
///   and the signing key must hash to a credential in that address.
///
/// # Returns
/// `true` if the signature is valid (and identity-bound, when an address is
/// present); `false` otherwise.
///
/// # Errors
/// * `InvalidCbor` - If the COSE Sign1 structure is malformed
/// * `InvalidAddress` - If a claimed/expected address cannot be parsed
bool verifyMessage(
        {required SignedMessage signedMessage, String? expectedAddress}) =>
    RustLib.instance.api.crateMessageVerifyMessage(
        signedMessage: signedMessage, expectedAddress: expectedAddress);

Future<bool> verifyMessageInternal(
        {required SignedMessage signedMessage, String? expectedAddress}) =>
    RustLib.instance.api.crateMessageVerifyMessageInternal(
        signedMessage: signedMessage, expectedAddress: expectedAddress);

/// A signed message with signature, public key, and address information.
class SignedMessage {
  /// Hex-encoded COSE Sign1 structure containing signature + payload
  final String coseSign1Hex;

  /// Hex-encoded public key (32 bytes)
  final String publicKeyHex;

  /// Optional: the address this key corresponds to (for context)
  final String? address;

  const SignedMessage({
    required this.coseSign1Hex,
    required this.publicKeyHex,
    this.address,
  });

  @override
  int get hashCode =>
      coseSign1Hex.hashCode ^ publicKeyHex.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedMessage &&
          runtimeType == other.runtimeType &&
          coseSign1Hex == other.coseSign1Hex &&
          publicKeyHex == other.publicKeyHex &&
          address == other.address;
}
