// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `text_datum`, `text_or_chunks`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Build CIP-25 v2 NFT auxiliary data (label 721) and return its CBOR hex.
///
/// Pass the result directly to `build_mint_tx` as `aux_data_cbor_hex`.
///
/// # Metadata structure
/// ```text
/// { 721: { "<policy_id>": { "<asset_name_utf8>": {
///   "name": "...",
///   "image": "ipfs://...",
///   "mediaType": "image/png",   -- optional
///   "description": "...",        -- optional
///   "version": 2
/// } } } }
/// ```
///
/// # Errors
/// - `InvalidParameter` if `asset_name_hex` is not valid UTF-8
/// - `CslError` if CSL metadata construction fails
String buildCip25Metadata({required List<Cip25Policy> policies}) =>
    RustLib.instance.api.crateMetadataBuildCip25Metadata(policies: policies);

/// Build a CIP-68 reference-token inline datum (Constr 0 [ fields_map, version ]).
///
/// CIP-68 stores token metadata as a Plutus datum on the (100) reference token
/// instead of in transaction metadata, enabling on-chain datum updates.
///
/// # Returns
/// `PlutusData` CBOR hex suitable for use as an inline datum.
///
/// # Structure
/// ```text
/// Constr 0 [
///   Map { "name"→bytes, "image"→bytes, "mediaType"→bytes, "description"→bytes },
///   Int(version)
/// ]
/// ```
String buildCip68Datum(
        {required String name,
        required String image,
        String? mediaType,
        String? description,
        required BigInt version}) =>
    RustLib.instance.api.crateMetadataBuildCip68Datum(
        name: name,
        image: image,
        mediaType: mediaType,
        description: description,
        version: version);

/// A single NFT asset within a CIP-25 policy metadata block.
class Cip25Asset {
  /// Hex-encoded asset name bytes (same bytes used in `MintSpec::assets`).
  final String assetNameHex;

  /// Human-readable display name.
  final String name;

  /// Token image URI, e.g. `"ipfs://Qm..."` or `"https://..."`.
  final String image;

  /// Optional MIME type, e.g. `"image/png"`.
  final String? mediaType;

  /// Optional description text.
  final String? description;

  const Cip25Asset({
    required this.assetNameHex,
    required this.name,
    required this.image,
    this.mediaType,
    this.description,
  });

  @override
  int get hashCode =>
      assetNameHex.hashCode ^
      name.hashCode ^
      image.hashCode ^
      mediaType.hashCode ^
      description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cip25Asset &&
          runtimeType == other.runtimeType &&
          assetNameHex == other.assetNameHex &&
          name == other.name &&
          image == other.image &&
          mediaType == other.mediaType &&
          description == other.description;
}

/// All NFT assets under one minting policy for CIP-25.
class Cip25Policy {
  /// 28-byte policy ID in lowercase hex (use `compute_policy_id`).
  final String policyIdHex;
  final List<Cip25Asset> assets;

  const Cip25Policy({
    required this.policyIdHex,
    required this.assets,
  });

  @override
  int get hashCode => policyIdHex.hashCode ^ assets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cip25Policy &&
          runtimeType == other.runtimeType &&
          policyIdHex == other.policyIdHex &&
          assets == other.assets;
}
