// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tx.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`

/// Build a single-signature native script keyed to `key_hash_hex`.
///
/// Returns the serialised `NativeScript` as CBOR hex.  The policy ID is the
/// Blake2b-224 hash of this bytes (use `compute_policy_id`).
String makePubkeyScript({required String keyHashHex}) =>
    RustLib.instance.api.crateMintingMakePubkeyScript(keyHashHex: keyHashHex);

/// Build an NFT minting policy: `ScriptAll [ ScriptPubKey, TimelockExpiry ]`.
///
/// Minting is only valid before `expiry_slot`; signing requires `key_hash_hex`.
/// This pattern produces a one-shot minting policy that provably stops at expiry,
/// giving collectors on-chain assurance of a fixed supply.
String makeTimelockExpiryScript(
        {required String keyHashHex, required BigInt expirySlot}) =>
    RustLib.instance.api.crateMintingMakeTimelockExpiryScript(
        keyHashHex: keyHashHex, expirySlot: expirySlot);

/// Compute the 28-byte policy ID (script hash) for a serialised native script.
///
/// # Arguments
/// - `native_script_cbor_hex`: CBOR hex produced by `make_pubkey_script` or
///   `make_timelock_expiry_script`
///
/// # Returns
/// 56-character lowercase hex string (28 bytes = Blake2b-224 of the script).
String computePolicyId({required String nativeScriptCborHex}) =>
    RustLib.instance.api
        .crateMintingComputePolicyId(nativeScriptCborHex: nativeScriptCborHex);

/// Build a transaction that mints or burns native tokens under native scripts.
///
/// # Arguments
/// - `inputs`: UTxOs to spend (ADA source for fees and min-ADA)
/// - `outputs`: explicit outputs, e.g. recipient of minted tokens; change is
///   computed automatically
/// - `change_address`: receives ADA change (and any un-assigned minted tokens)
/// - `mint_specs`: one entry per minting policy; assets are positive (mint) or
///   negative (burn)
/// - `aux_data_cbor_hex`: pre-built CIP-25/68 auxiliary data; use
///   `build_cip25_metadata` to produce this
/// - `ttl`: slot deadline (`None` = no expiry)
/// - `params`: current protocol parameters
///
/// # Errors
/// - `InvalidParameter` if `inputs` or `mint_specs` are empty
/// - `InvalidAddress` if any address is malformed
/// - `TxBuild` if CSL builder fails (e.g. insufficient funds)
BuiltMintTx buildMintTx(
        {required List<TxInput> inputs,
        required List<TxOutput> outputs,
        required String changeAddress,
        required List<MintSpec> mintSpecs,
        String? auxDataCborHex,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateMintingBuildMintTx(
        inputs: inputs,
        outputs: outputs,
        changeAddress: changeAddress,
        mintSpecs: mintSpecs,
        auxDataCborHex: auxDataCborHex,
        ttl: ttl,
        params: params);

/// Result of a successfully built minting transaction.
class BuiltMintTx {
  /// Serialised transaction body (CBOR hex), ready for signing.
  final String txBodyCborHex;

  /// Auxiliary data (CBOR hex) if metadata was attached; `None` otherwise.
  /// Pass this to `sign_tx_with_metadata` so it is included in the final tx.
  final String? auxDataCborHex;

  /// Partial witness set (CBOR hex) that CSL assembled while building — it
  /// carries the minting policy's **native script**. Pass this to
  /// `sign_tx_with_metadata` so signing merges the vkey witnesses into it
  /// instead of dropping the script (a tx missing the policy script is
  /// rejected on submission with `MissingScriptWitnessesUTXOW`).
  final String? witnessSetCborHex;

  /// Blake2b-256 hash of the serialised body.
  final String txHash;

  /// Computed fee in lovelace.
  final BigInt fee;

  const BuiltMintTx({
    required this.txBodyCborHex,
    this.auxDataCborHex,
    this.witnessSetCborHex,
    required this.txHash,
    required this.fee,
  });

  @override
  int get hashCode =>
      txBodyCborHex.hashCode ^
      auxDataCborHex.hashCode ^
      witnessSetCborHex.hashCode ^
      txHash.hashCode ^
      fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuiltMintTx &&
          runtimeType == other.runtimeType &&
          txBodyCborHex == other.txBodyCborHex &&
          auxDataCborHex == other.auxDataCborHex &&
          witnessSetCborHex == other.witnessSetCborHex &&
          txHash == other.txHash &&
          fee == other.fee;
}

/// A single asset to mint (positive quantity) or burn (negative quantity).
class MintAsset {
  /// Hex-encoded asset name bytes (max 32 bytes → max 64 hex chars).
  final String assetNameHex;

  /// Positive = mint, negative = burn.
  final PlatformInt64 quantity;

  const MintAsset({
    required this.assetNameHex,
    required this.quantity,
  });

  @override
  int get hashCode => assetNameHex.hashCode ^ quantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintAsset &&
          runtimeType == other.runtimeType &&
          assetNameHex == other.assetNameHex &&
          quantity == other.quantity;
}

/// Specification for minting/burning assets under one native-script policy.
class MintSpec {
  /// CBOR hex of the serialised `NativeScript` — use one of the constructor
  /// helpers or any externally-built script.
  final String policyScriptCborHex;
  final List<MintAsset> assets;

  const MintSpec({
    required this.policyScriptCborHex,
    required this.assets,
  });

  @override
  int get hashCode => policyScriptCborHex.hashCode ^ assets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MintSpec &&
          runtimeType == other.runtimeType &&
          policyScriptCborHex == other.policyScriptCborHex &&
          assets == other.assets;
}
