// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tx.dart';

// These functions are ignored because they are not marked as `pub`: `build_conway_cost_models`

/// Encode an integer as `PlutusData` CBOR hex.
///
/// Handles the full `i64` range; large integers (> i32 range) are encoded as
/// Plutus `I` tags using the CBOR big-integer encoding.
String plutusDataInt({required PlatformInt64 n}) =>
    RustLib.instance.api.cratePlutusPlutusDataInt(n: n);

/// Encode arbitrary bytes (hex input) as `PlutusData` CBOR hex.
String plutusDataBytes({required String hexData}) =>
    RustLib.instance.api.cratePlutusPlutusDataBytes(hexData: hexData);

/// Encode a constructor application as `PlutusData` CBOR hex.
///
/// # Arguments
/// - `constructor`: alternative index (0-based)
/// - `fields_cbor_hex`: ordered list of `PlutusData` CBOR hex values produced
///   by the other `plutus_data_*` helpers
String plutusDataConstr(
        {required BigInt constructor, required List<String> fieldsCborHex}) =>
    RustLib.instance.api.cratePlutusPlutusDataConstr(
        constructor: constructor, fieldsCborHex: fieldsCborHex);

/// Encode a `PlutusData` list as CBOR hex.
String plutusDataList({required List<String> itemsCborHex}) =>
    RustLib.instance.api.cratePlutusPlutusDataList(itemsCborHex: itemsCborHex);

/// Verify that a CBOR hex string represents valid `PlutusData`.
///
/// Returns the same hex on success, or an error describing why it is invalid.
/// Useful for validating externally-sourced datum/redeemer values.
String validatePlutusData({required String cborHex}) =>
    RustLib.instance.api.cratePlutusValidatePlutusData(cborHex: cborHex);

/// Build a transaction spending one or more Plutus script UTxOs.
///
/// # Arguments
/// - `script_inputs`: Plutus-locked UTxOs, each with witness data
/// - `regular_inputs`: ordinary (key-locked) UTxOs also consumed (e.g. for fees)
/// - `outputs`: outputs to create
/// - `change_address`: receives ADA change
/// - `collateral_inputs`: pure-ADA UTxOs used as collateral (required for Plutus)
/// - `reference_inputs`: read-only reference UTxOs (CIP-31); not consumed
/// - `ttl`: optional slot deadline
/// - `params`: protocol parameters
///
/// # Errors
/// - `InvalidParameter` if `script_inputs` or `collateral_inputs` are empty
/// - `InvalidCbor` if any datum/redeemer/script CBOR is malformed
/// - `TxBuild` if CSL builder or script-data-hash computation fails
BuiltTx buildScriptTx(
        {required List<PlutusInput> scriptInputs,
        required List<TxInput> regularInputs,
        required List<TxOutput> outputs,
        required String changeAddress,
        required List<TxInput> collateralInputs,
        required List<TxInput> referenceInputs,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.cratePlutusBuildScriptTx(
        scriptInputs: scriptInputs,
        regularInputs: regularInputs,
        outputs: outputs,
        changeAddress: changeAddress,
        collateralInputs: collateralInputs,
        referenceInputs: referenceInputs,
        ttl: ttl,
        params: params);

/// A script-locked UTxO to spend, with its witness data.
class PlutusInput {
  /// The UTxO to spend.
  final TxInput txInput;

  /// Flat-encoded script CBOR hex (the `PlutusScript` CBOR, not double-encoded).
  final String scriptCborHex;
  final PlutusScriptVersion scriptVersion;

  /// `PlutusData` CBOR hex for the datum embedded in the witness.
  final String datumCborHex;

  /// `PlutusData` CBOR hex for the redeemer.
  final String redeemerCborHex;

  /// Execution unit memory budget.
  final BigInt exUnitsMem;

  /// Execution unit step budget.
  final BigInt exUnitsSteps;

  const PlutusInput({
    required this.txInput,
    required this.scriptCborHex,
    required this.scriptVersion,
    required this.datumCborHex,
    required this.redeemerCborHex,
    required this.exUnitsMem,
    required this.exUnitsSteps,
  });

  @override
  int get hashCode =>
      txInput.hashCode ^
      scriptCborHex.hashCode ^
      scriptVersion.hashCode ^
      datumCborHex.hashCode ^
      redeemerCborHex.hashCode ^
      exUnitsMem.hashCode ^
      exUnitsSteps.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlutusInput &&
          runtimeType == other.runtimeType &&
          txInput == other.txInput &&
          scriptCborHex == other.scriptCborHex &&
          scriptVersion == other.scriptVersion &&
          datumCborHex == other.datumCborHex &&
          redeemerCborHex == other.redeemerCborHex &&
          exUnitsMem == other.exUnitsMem &&
          exUnitsSteps == other.exUnitsSteps;
}

/// Plutus script language version.
enum PlutusScriptVersion {
  v2,
  v3,
  ;
}
