// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_header`, `decrypt_seed_internal`, `derive_key`, `encrypt_seed_internal`, `validate_kdf_params`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`

/// The recommended default Argon2id parameters for this build.
KdfParams defaultKdfParams() =>
    RustLib.instance.api.crateSeedDefaultKdfParams();

/// Encrypt a recovery secret (e.g. a BIP-39 mnemonic) with the default,
/// device-appropriate Argon2id parameters.
///
/// - `secret`: the plaintext to protect (mnemonic phrase or other UTF-8 secret).
/// - `password`: the user's password; the sole gate to recovery.
///
/// Returns a hex container safe to persist. Salt and nonce are freshly random
/// per call, so encrypting the same secret twice yields different blobs.
EncryptedSeed encryptSeed({required String secret, required String password}) =>
    RustLib.instance.api
        .crateSeedEncryptSeed(secret: secret, password: password);

/// Like [`encrypt_seed`] but with explicit Argon2id cost parameters (tune via
/// [`benchmark_kdf`]). Parameters are stored in the header, so decryption does
/// not need them supplied again.
EncryptedSeed encryptSeedWithParams(
        {required String secret,
        required String password,
        required int memKib,
        required int iterations,
        required int parallelism}) =>
    RustLib.instance.api.crateSeedEncryptSeedWithParams(
        secret: secret,
        password: password,
        memKib: memKib,
        iterations: iterations,
        parallelism: parallelism);

/// Decrypt a `CFS1` container produced by [`encrypt_seed`]. Returns the original
/// UTF-8 secret. A wrong password and a tampered blob are indistinguishable —
/// both surface as an authentication failure (fails closed, never partial).
String decryptSeed({required String blobHex, required String password}) =>
    RustLib.instance.api
        .crateSeedDecryptSeed(blobHex: blobHex, password: password);

/// Measure the wall-clock cost (milliseconds) of the Argon2id KDF for the given
/// parameters on this device. Use to tune params to a target unlock latency.
BigInt benchmarkKdf(
        {required int memKib,
        required int iterations,
        required int parallelism}) =>
    RustLib.instance.api.crateSeedBenchmarkKdf(
        memKib: memKib, iterations: iterations, parallelism: parallelism);

/// Result of [`encrypt_seed`] — the at-rest container plus an echo of the KDF
/// parameters that were actually used (also embedded in `blob_hex`).
class EncryptedSeed {
  /// Versioned, self-describing `CFS1` container, hex-encoded. Store this.
  final String blobHex;

  /// KDF parameters used (informational; authoritative copy is in `blob_hex`).
  final KdfParams kdf;

  const EncryptedSeed({
    required this.blobHex,
    required this.kdf,
  });

  @override
  int get hashCode => blobHex.hashCode ^ kdf.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncryptedSeed &&
          runtimeType == other.runtimeType &&
          blobHex == other.blobHex &&
          kdf == other.kdf;
}

/// Argon2id cost parameters. Embedded in every ciphertext header so decryption
/// is self-contained (it always uses the params the blob was written with).
class KdfParams {
  /// Memory cost in KiB.
  final int memKib;

  /// Time cost (number of passes).
  final int iterations;

  /// Degree of parallelism (lanes).
  final int parallelism;

  const KdfParams({
    required this.memKib,
    required this.iterations,
    required this.parallelism,
  });

  static Future<KdfParams> default_() =>
      RustLib.instance.api.crateSeedKdfParamsDefault();

  @override
  int get hashCode =>
      memKib.hashCode ^ iterations.hashCode ^ parallelism.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KdfParams &&
          runtimeType == other.runtimeType &&
          memKib == other.memKib &&
          iterations == other.iterations &&
          parallelism == other.parallelism;
}
