// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `compute_blake2b256_hash`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Sign a transaction body and attach optional auxiliary data (metadata).
///
/// Use this instead of `sign_tx` when the transaction carries CIP-25/68 metadata
/// produced by `build_cip25_metadata`.  The `aux_data_cbor_hex` must be the
/// same value returned by `build_mint_tx.aux_data_cbor_hex`.
///
/// # Arguments
/// * `tx_body_cbor_hex` - Serialised transaction body (CBOR hex)
/// * `payment_keys_hex` - Payment keys as bech32 strings
/// * `aux_data_cbor_hex` - Optional auxiliary-data CBOR hex
///
/// # Errors
/// * `InvalidKey` - If a key is malformed
/// * `InvalidCbor` - If the body or aux data CBOR is malformed
SignedTx signTxWithMetadata(
        {required String txBodyCborHex,
        required List<String> paymentKeysHex,
        String? auxDataCborHex,
        String? baseWitnessSetCborHex}) =>
    RustLib.instance.api.crateSignSignTxWithMetadata(
        txBodyCborHex: txBodyCborHex,
        paymentKeysHex: paymentKeysHex,
        auxDataCborHex: auxDataCborHex,
        baseWitnessSetCborHex: baseWitnessSetCborHex);

Future<SignedTx> signTxWithMetadataInternal(
        {required String txBodyCborHex,
        required List<String> paymentKeysHex,
        String? auxDataCborHex,
        String? baseWitnessSetCborHex}) =>
    RustLib.instance.api.crateSignSignTxWithMetadataInternal(
        txBodyCborHex: txBodyCborHex,
        paymentKeysHex: paymentKeysHex,
        auxDataCborHex: auxDataCborHex,
        baseWitnessSetCborHex: baseWitnessSetCborHex);

/// Sign a transaction body with one or more payment keys.
///
/// Takes a serialized transaction body and a list of payment keys (bech32-encoded ed25519
/// extended keys), derives public keys, signs the body hash, and produces a complete
/// `TransactionWitnessSet` containing vkey witnesses.
///
/// # Arguments
/// * `tx_body_cbor_hex` - The transaction body serialized as CBOR hex
/// * `payment_keys_hex` - Payment keys as bech32 strings (treated as sensitive)
///
/// # Returns
/// A `SignedTx` containing the full signed transaction in CBOR hex and its hash.
///
/// # Error handling
/// * `InvalidKey` - If a payment key cannot be decoded or has invalid format
/// * `InvalidCbor` - If the transaction body CBOR is malformed
///
/// # Security notes
/// Keys are cleared as soon as public keys are extracted. The returned witness set
/// contains no key material (only public key hashes).
SignedTx signTx(
        {required String txBodyCborHex,
        required List<String> paymentKeysHex}) =>
    RustLib.instance.api.crateSignSignTx(
        txBodyCborHex: txBodyCborHex, paymentKeysHex: paymentKeysHex);

Future<SignedTx> signTxInternal(
        {required String txBodyCborHex,
        required List<String> paymentKeysHex}) =>
    RustLib.instance.api.crateSignSignTxInternal(
        txBodyCborHex: txBodyCborHex, paymentKeysHex: paymentKeysHex);

/// A signed transaction ready for submission.
class SignedTx {
  /// Complete transaction (body + witness set + auxiliary_data) in CBOR hex.
  final String txCborHex;

  /// Transaction hash (hash of the serialized body).
  final String txHash;

  const SignedTx({
    required this.txCborHex,
    required this.txHash,
  });

  @override
  int get hashCode => txCborHex.hashCode ^ txHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignedTx &&
          runtimeType == other.runtimeType &&
          txCborHex == other.txCborHex &&
          txHash == other.txHash;
}
