// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tx.dart';

// These functions are ignored because they are not marked as `pub`: `add_inputs`, `finalise`, `make_tx_builder`, `stake_credential`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Build a stake key registration transaction.
///
/// Costs `key_deposit` lovelace (typically 2 ADA on mainnet). The deposit is
/// returned upon deregistration.  The stake key must be registered before it
/// can be delegated to a pool.
///
/// # Arguments
/// - `stake_key_hash_hex`: 56-char hex Blake2b-224 hash of the stake public key
/// - `inputs`: UTxOs covering the deposit + fees
/// - `change_address`: bech32 address for ADA change
/// - `network_id`: 0 = testnet, 1 = mainnet
/// - `ttl`: optional slot deadline
/// - `params`: current protocol parameters
///
/// # Errors
/// - `InvalidParameter` if inputs are empty or stake_key_hash_hex is invalid
/// - `InvalidAddress` if any address is malformed
/// - `TxBuild` if the builder fails
BuiltStakingTx buildStakeRegistrationTx(
        {required String stakeKeyHashHex,
        required List<TxInput> inputs,
        required String changeAddress,
        required int networkId,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateStakingBuildStakeRegistrationTx(
        stakeKeyHashHex: stakeKeyHashHex,
        inputs: inputs,
        changeAddress: changeAddress,
        networkId: networkId,
        ttl: ttl,
        params: params);

/// Build a stake delegation transaction.
///
/// Delegates the stake key to the pool identified by `pool_keyhash_hex`.
/// The stake key must already be registered on-chain.  No deposit is required.
///
/// # Arguments
/// - `stake_key_hash_hex`: 56-char hex of the stake key hash
/// - `pool_keyhash_hex`: 56-char hex of the target pool's operator key hash
/// - `inputs`: UTxOs covering the fee
/// - `change_address`: bech32 address for ADA change
/// - `network_id`: 0 = testnet, 1 = mainnet
/// - `ttl`: optional slot deadline
/// - `params`: current protocol parameters
BuiltStakingTx buildDelegationTx(
        {required String stakeKeyHashHex,
        required String poolKeyhashHex,
        required List<TxInput> inputs,
        required String changeAddress,
        required int networkId,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateStakingBuildDelegationTx(
        stakeKeyHashHex: stakeKeyHashHex,
        poolKeyhashHex: poolKeyhashHex,
        inputs: inputs,
        changeAddress: changeAddress,
        networkId: networkId,
        ttl: ttl,
        params: params);

/// Build a reward withdrawal transaction.
///
/// Withdraws accumulated staking rewards from the reward address to `change_address`.
/// `reward_amount` must exactly match the on-chain withdrawable balance (use
/// `fetchAccountInfo` to query this before building).
///
/// # Arguments
/// - `stake_key_hash_hex`: 56-char hex of the stake key hash
/// - `reward_amount`: exact lovelace amount to withdraw (may be 0)
/// - `inputs`: UTxOs covering the fee (rewards reduce the net fee burden)
/// - `change_address`: bech32 address; also receives the withdrawn rewards + ADA change
/// - `network_id`: 0 = testnet, 1 = mainnet
/// - `ttl`: optional slot deadline
/// - `params`: current protocol parameters
BuiltStakingTx buildRewardWithdrawalTx(
        {required String stakeKeyHashHex,
        required BigInt rewardAmount,
        required List<TxInput> inputs,
        required String changeAddress,
        required int networkId,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateStakingBuildRewardWithdrawalTx(
        stakeKeyHashHex: stakeKeyHashHex,
        rewardAmount: rewardAmount,
        inputs: inputs,
        changeAddress: changeAddress,
        networkId: networkId,
        ttl: ttl,
        params: params);

/// Build a stake key deregistration transaction.
///
/// Returns the `key_deposit` lovelace to `change_address`.  After deregistration
/// the stake key is no longer delegated and must be re-registered to earn rewards.
///
/// # Arguments
/// - `stake_key_hash_hex`: 56-char hex of the stake key hash
/// - `inputs`: UTxOs covering the fee (the returned deposit subsidises it)
/// - `change_address`: bech32 address; receives the returned deposit + ADA change
/// - `network_id`: 0 = testnet, 1 = mainnet
/// - `ttl`: optional slot deadline
/// - `params`: current protocol parameters
BuiltStakingTx buildStakeDeregistrationTx(
        {required String stakeKeyHashHex,
        required List<TxInput> inputs,
        required String changeAddress,
        required int networkId,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateStakingBuildStakeDeregistrationTx(
        stakeKeyHashHex: stakeKeyHashHex,
        inputs: inputs,
        changeAddress: changeAddress,
        networkId: networkId,
        ttl: ttl,
        params: params);

/// Compute the bech32 stake address (reward address) for a stake key hash.
///
/// # Arguments
/// - `stake_key_hash_hex`: 56-char hex Blake2b-224 hash of the stake public key
/// - `is_testnet`: true for testnet (`stake_test1...`), false for mainnet (`stake1...`)
///
/// # Returns
/// The bech32 reward address string.
String computeStakeAddress(
        {required String stakeKeyHashHex, required bool isTestnet}) =>
    RustLib.instance.api.crateStakingComputeStakeAddress(
        stakeKeyHashHex: stakeKeyHashHex, isTestnet: isTestnet);

/// Result of a successfully built staking transaction.
class BuiltStakingTx {
  /// Serialised transaction body (CBOR hex), ready for signing.
  final String txBodyCborHex;

  /// Blake2b-256 hash of the body.
  final String txHash;

  /// Computed fee in lovelace.
  final BigInt fee;

  /// Deposit change in lovelace:
  /// - negative = deposit paid (registration)
  /// - positive = deposit returned (deregistration)
  /// - 0 = neutral (delegation, withdrawal)
  final PlatformInt64 depositChange;

  const BuiltStakingTx({
    required this.txBodyCborHex,
    required this.txHash,
    required this.fee,
    required this.depositChange,
  });

  @override
  int get hashCode =>
      txBodyCborHex.hashCode ^
      txHash.hashCode ^
      fee.hashCode ^
      depositChange.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuiltStakingTx &&
          runtimeType == other.runtimeType &&
          txBodyCborHex == other.txBodyCborHex &&
          txHash == other.txHash &&
          fee == other.fee &&
          depositChange == other.depositChange;
}
