// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `hex_to_bytes`, `input_to_csl`, `map_csl_error`, `map_deserialize_error`, `output_to_csl`, `value_to_csl`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// Build a transaction with manual input/output selection.
///
/// # Arguments
/// - `inputs`: UTxOs to spend
/// - `outputs`: outputs to create
/// - `change_address`: where to send change (bech32)
/// - `ttl`: optional slot number after which the tx is invalid
/// - `params`: protocol parameters from the blockchain
///
/// # Errors
/// - `InvalidAddress`: if any address is malformed
/// - `InvalidParameter`: if inputs, outputs, or params are invalid
/// - `TxBuild`: if the builder encounters an error (e.g., insufficient funds, change < min_ada)
BuiltTx buildTx(
        {required List<TxInput> inputs,
        required List<TxOutput> outputs,
        required String changeAddress,
        BigInt? ttl,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateTxBuildTx(
        inputs: inputs,
        outputs: outputs,
        changeAddress: changeAddress,
        ttl: ttl,
        params: params);

/// Compute the minimum ADA required for an output.
///
/// Uses the CSL helper to account for CBOR serialization size and the UTxO
/// entry cost (160 bytes overhead in Babbage).
///
/// # Arguments
/// - `output`: the output to check
/// - `coins_per_utxo_byte`: from protocol parameters
///
/// # Errors
/// - `InvalidAddress`: if the address is malformed
/// - `CslError`: if CSL's min_ada calculator fails
BigInt minAdaForOutput(
        {required TxOutput output, required BigInt coinsPerUtxoByte}) =>
    RustLib.instance.api.crateTxMinAdaForOutput(
        output: output, coinsPerUtxoByte: coinsPerUtxoByte);

/// Estimate the fee for a transaction body.
///
/// Fee = `min_fee_a * tx_size_bytes + min_fee_b + (witness_count * witness_overhead)`.
///
/// # Arguments
/// - `tx_body_cbor_hex`: hex-encoded transaction body CBOR
/// - `witness_count`: expected number of vkey witnesses
/// - `params`: protocol parameters
///
/// # Errors
/// - `InvalidParameter`: if the hex is invalid
/// - `TxBuild`: if fee computation fails
BigInt estimateFee(
        {required String txBodyCborHex,
        required int witnessCount,
        required ProtocolParams params}) =>
    RustLib.instance.api.crateTxEstimateFee(
        txBodyCborHex: txBodyCborHex,
        witnessCount: witnessCount,
        params: params);

/// Result of a successfully built transaction.
class BuiltTx {
  final String txBodyCborHex;
  final String txHash;
  final BigInt fee;

  const BuiltTx({
    required this.txBodyCborHex,
    required this.txHash,
    required this.fee,
  });

  @override
  int get hashCode => txBodyCborHex.hashCode ^ txHash.hashCode ^ fee.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BuiltTx &&
          runtimeType == other.runtimeType &&
          txBodyCborHex == other.txBodyCborHex &&
          txHash == other.txHash &&
          fee == other.fee;
}

/// Represents a single native token quantity.
class NativeAsset {
  final String policyId;
  final String assetName;
  final BigInt quantity;

  const NativeAsset({
    required this.policyId,
    required this.assetName,
    required this.quantity,
  });

  @override
  int get hashCode =>
      policyId.hashCode ^ assetName.hashCode ^ quantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NativeAsset &&
          runtimeType == other.runtimeType &&
          policyId == other.policyId &&
          assetName == other.assetName &&
          quantity == other.quantity;
}

/// Protocol parameters required for transaction building.
class ProtocolParams {
  final BigInt minFeeA;
  final BigInt minFeeB;
  final BigInt coinsPerUtxoByte;
  final int maxTxSize;
  final BigInt poolDeposit;
  final BigInt keyDeposit;
  final int maxValSize;

  const ProtocolParams({
    required this.minFeeA,
    required this.minFeeB,
    required this.coinsPerUtxoByte,
    required this.maxTxSize,
    required this.poolDeposit,
    required this.keyDeposit,
    required this.maxValSize,
  });

  @override
  int get hashCode =>
      minFeeA.hashCode ^
      minFeeB.hashCode ^
      coinsPerUtxoByte.hashCode ^
      maxTxSize.hashCode ^
      poolDeposit.hashCode ^
      keyDeposit.hashCode ^
      maxValSize.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProtocolParams &&
          runtimeType == other.runtimeType &&
          minFeeA == other.minFeeA &&
          minFeeB == other.minFeeB &&
          coinsPerUtxoByte == other.coinsPerUtxoByte &&
          maxTxSize == other.maxTxSize &&
          poolDeposit == other.poolDeposit &&
          keyDeposit == other.keyDeposit &&
          maxValSize == other.maxValSize;
}

/// Represents a single transaction input (UTxO).
class TxInput {
  final String txHash;
  final int outputIndex;
  final String address;
  final Value value;

  const TxInput({
    required this.txHash,
    required this.outputIndex,
    required this.address,
    required this.value,
  });

  @override
  int get hashCode =>
      txHash.hashCode ^
      outputIndex.hashCode ^
      address.hashCode ^
      value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxInput &&
          runtimeType == other.runtimeType &&
          txHash == other.txHash &&
          outputIndex == other.outputIndex &&
          address == other.address &&
          value == other.value;
}

/// Represents a single transaction output.
class TxOutput {
  final String address;
  final Value value;

  const TxOutput({
    required this.address,
    required this.value,
  });

  @override
  int get hashCode => address.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TxOutput &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          value == other.value;
}

/// Represents a monetary value: ADA (lovelace) + optional native assets.
class Value {
  final BigInt coin;
  final List<NativeAsset> assets;

  const Value({
    required this.coin,
    required this.assets,
  });

  @override
  int get hashCode => coin.hashCode ^ assets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Value &&
          runtimeType == other.runtimeType &&
          coin == other.coin &&
          assets == other.assets;
}
