// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'error.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

KeyDerivationResult deriveKeysFromMnemonic(
        {required String mnemonic,
        required String passphrase,
        required int accountIndex,
        required bool isTestnet}) =>
    RustLib.instance.api.crateWalletDeriveKeysFromMnemonic(
        mnemonic: mnemonic,
        passphrase: passphrase,
        accountIndex: accountIndex,
        isTestnet: isTestnet);

Future<KeyDerivationResult> deriveKeysFromMnemonicInternal(
        {required String mnemonic,
        required String passphrase,
        required int accountIndex,
        required bool isTestnet}) =>
    RustLib.instance.api.crateWalletDeriveKeysFromMnemonicInternal(
        mnemonic: mnemonic,
        passphrase: passphrase,
        accountIndex: accountIndex,
        isTestnet: isTestnet);

String deriveAccountKey(
        {required String accountKey, required int role, required int index}) =>
    RustLib.instance.api.crateWalletDeriveAccountKey(
        accountKey: accountKey, role: role, index: index);

Future<String> deriveAccountKeyInternal(
        {required String accountKey, required int role, required int index}) =>
    RustLib.instance.api.crateWalletDeriveAccountKeyInternal(
        accountKey: accountKey, role: role, index: index);

class KeyDerivationResult {
  final String accountKey;
  final String paymentKey;
  final String stakeKey;

  /// Blake2b-224 hash of the payment public key (28 bytes = 56 hex chars).
  /// Use as `key_hash_hex` argument for `make_pubkey_script`.
  final String paymentKeyHash;

  const KeyDerivationResult({
    required this.accountKey,
    required this.paymentKey,
    required this.stakeKey,
    required this.paymentKeyHash,
  });

  @override
  int get hashCode =>
      accountKey.hashCode ^
      paymentKey.hashCode ^
      stakeKey.hashCode ^
      paymentKeyHash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyDerivationResult &&
          runtimeType == other.runtimeType &&
          accountKey == other.accountKey &&
          paymentKey == other.paymentKey &&
          stakeKey == other.stakeKey &&
          paymentKeyHash == other.paymentKeyHash;
}
