// Stages the in-browser conformance harness into ./build:
//   • copies the CML + cardano-message-signing browser WASM builds
//   • embeds the canonical golden vectors + a BIP-39 entropy bridge as data.js
// Run AFTER `dart compile js` has produced build/harness.js. See README.md.
import { copyFileSync, readFileSync, writeFileSync, mkdirSync } from 'fs';
import { execSync } from 'child_process';

const here = new URL('./', import.meta.url);
const build = new URL('./build/', here);
mkdirSync(build, { recursive: true });

// 1. Resolve & copy the browser WASM builds from this dir's node_modules.
//    (run `npm install` in tool/web_conformance first)
const nm = new URL('./node_modules/', here);
const copies = [
  ['@dcspark/cardano-multiplatform-lib-browser/cardano_multiplatform_lib_bg.js', 'cml_bg.js'],
  ['@dcspark/cardano-multiplatform-lib-browser/cardano_multiplatform_lib_bg.wasm', 'cml_bg.wasm'],
  ['@emurgo/cardano-message-signing-browser/cardano_message_signing_bg.js', 'ms_bg.js'],
  ['@emurgo/cardano-message-signing-browser/cardano_message_signing_bg.wasm', 'ms_bg.wasm'],
];
for (const [src, dst] of copies) {
  copyFileSync(new URL(src, nm), new URL(dst, build));
}

// wasm-bindgen bundler-target `_bg.js` declares its wasm import under a relative
// module specifier that must resolve in the browser. Rewrite those specifiers to
// the staged sibling filenames so plain ESM import works without a bundler.
function patchBg(file, wasmName) {
  const p = new URL(file, build);
  let js = readFileSync(p, 'utf8');
  // The harness imports `_bg.js` and instantiates the wasm manually, so the only
  // requirement is that the file is importable ESM — which it already is. No
  // rewrite of internal specifiers is needed for the manual-instantiation path.
  writeFileSync(p, js);
}
patchBg('cml_bg.js', 'cml_bg.wasm');
patchBg('ms_bg.js', 'ms_bg.wasm');

// 2. Embed the canonical golden vectors + entropy bridge.
const golden = readFileSync(
  new URL('../../dart/test/conformance/golden_cbor.json', here), 'utf8');

// BIP-39 mnemonic→entropy for the single test vector. The bridge is host-provided
// by design (project policy keeps mnemonic crypto out of Dart); here it is pinned
// to the test mnemonic so deriveKeys' CML derivation path runs in-browser. The
// part under test is CML's BIP-32 derivation, not the wordlist lookup.
const TEST_MNEMONIC =
  'test walk nut penalty hip pave soap entry language right filter choice';
const TEST_ENTROPY = 'df9ed25ed146bf43336a5d7cf7395994';

const data = `// generated by build.mjs — do not edit
globalThis.GOLDEN_JSON = ${JSON.stringify(golden)};
globalThis.CFL_mnemonicToEntropy = (m) =>
  m === ${JSON.stringify(TEST_MNEMONIC)} ? ${JSON.stringify(TEST_ENTROPY)}
    : (() => { throw new Error('entropy bridge: unknown mnemonic'); })();
globalThis.CONFORMANCE_RESULT = '(harness did not run)';
`;
writeFileSync(new URL('data.js', build), data);

// 3. Stage the loader page.
copyFileSync(new URL('index.html', here), new URL('index.html', build));

console.log('Staged build/. Serve it and open index.html (see README.md).');
